name: Generate Space Shooter Game
on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write       # Required to commit the generated GIF

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'shooter.gif'
          strategy: 'random'
          fps: 40
